import{ENABLED_SYMBOLS,TIMEFRAMES,DEFAULT_TIMEFRAME,resolveSymbol,timeframe,APP_VERSION}from"./config.js";
import{fetchKlines,marketStream,mergeRows}from"./binance.js";
import{getSetting,setSetting,listDrawings,replaceDrawings,deleteDrawings,getMarketCache,setMarketCache,exportLocalData,importLocalData}from"./storage.js";
import{ChartView}from"./chart.js";
import{aggregateBiweekly,replayCutIndex}from"./math.js";
import{createCloudSync}from"./firebase-sync.js";

const $=s=>document.querySelector(s),clone=value=>structuredClone(value),state={symbol:null,timeframe:DEFAULT_TIMEFRAME,raw:[],rows:[],stopStream:null,loading:false,loadingOlder:false,historyPast:[],historyFuture:[],authUser:null,cloud:null,replay:{selecting:false,active:false,cut:null,time:null,timer:null,speed:1,loadingFuture:false}};
const els={symbol:$("#symbol"),tfs:$("#timeframes"),status:$("#status"),ohlc:$("#ohlc"),countdown:$("#countdown"),replay:$("#replay"),controls:$("#replay-controls"),bars:$("#visible-bars"),auth:$("#auth-button"),authLabel:$("#auth-label"),authAvatar:$("#auth-avatar")};
let toastTimer;
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2400)}
function setStatus(kind,text){els.status.className=`status ${kind}`;els.status.querySelector("b").textContent=text}
function setSyncStatus(kind,error){els.auth.dataset.sync=kind;els.auth.title=kind==="synced"?"Đã đồng bộ":kind==="syncing"?"Đang đồng bộ":kind==="error"?`Lỗi đồng bộ: ${error?.message||"không xác định"}`:"Đăng nhập Google để đồng bộ"}
function setAuthUser(user){state.authUser=user;els.authLabel.textContent=user?.displayName?.split(" ")[0]||"Đăng nhập";els.authAvatar.hidden=!user?.photoURL;if(user?.photoURL)els.authAvatar.src=user.photoURL;els.auth.setAttribute("aria-label",user?`Tài khoản ${user.email}. Nhấn để đăng xuất`:"Đăng nhập Google để đồng bộ")}
async function applySyncedData(kind,row){
  if(kind==="reset"){chart.setDrawings([]);state.historyPast=[];state.historyFuture=[];updateHistoryButtons();return}
  if(kind==="drawing"){if(row.symbol===state.symbol)chart.setDrawings(await listDrawings(state.symbol));return}
  if(row.id==="lastSymbol"&&ENABLED_SYMBOLS.includes(row.value)&&row.value!==state.symbol){resetReplay();state.symbol=row.value;els.symbol.value=row.value;updateUrl();await load()}
  else if(row.id==="timeframe"&&TIMEFRAMES.some(x=>x.label===row.value)&&row.value!==state.timeframe){state.timeframe=row.value;for(const b of els.tfs.children)b.classList.toggle("active",b.dataset.tf===row.value);await load()}
  else if(row.id==="visibleBars"){chart.visibleBars=Math.max(20,Math.min(1000,+row.value||240));els.bars.value=chart.visibleBars;chart.render()}
  else if(row.id==="pricePercent"){const value=Math.max(35,Math.min(80,+row.value||64));document.querySelector(".price-pane").style.flex=String(value);document.querySelector(".rsi-pane").style.flex=String(100-value);chart.render()}
  else if(row.id==="drawingDefaults")chart.setDefaults(row.value);
}
let cloudSetup;
async function setupCloud(){return cloudSetup ||= createCloudSync({onAuth:setAuthUser,onStatus:setSyncStatus,onData:(kind,row)=>void applySyncedData(kind,row)}).then(cloud=>(state.cloud=cloud,cloud)).catch(error=>{cloudSetup=null;setSyncStatus("error",error);throw error})}
function updateUrl(){const url=new URL(location.href);url.searchParams.set("symbol",state.symbol);history.replaceState(null,"",url)}
function currentTf(){return timeframe(state.timeframe)}
function normalize(rows){return currentTf().biweekly?aggregateBiweekly(rows):rows}
function displayRows(){return state.replay.active?state.rows.slice(0,state.replay.cut):state.rows}
const chart=new ChartView($("#price"),$("#rsi"),{
  symbol:()=>state.symbol,
  hover:row=>updateOhlc(row||displayRows().at(-1)),
  zoom:value=>{els.bars.value=value;void setSetting("visibleBars",value)},
  older:()=>void loadOlder(),
  text:current=>Promise.resolve(prompt("Nội dung",current||"") ?? null),
  tool:tool=>{for(const button of document.querySelectorAll("[data-tool]"))button.classList.toggle("active",tool===button.dataset.tool)},
  select:(drawing,point)=>showDrawingMenu(drawing,point),
  change:async(before,after)=>commitDrawings(before,after),
  selectReplay:index=>{if(!state.replay.selecting)return false;if(index<=0)return true;state.replay.selecting=false;state.replay.active=true;state.replay.time=state.rows[index]?.time;state.replay.cut=replayCutIndex(state.rows,state.replay.time);syncReplay(true);return true}
});

async function commitDrawings(before,after,{history=true}={}){if(JSON.stringify(before)===JSON.stringify(after))return;if(history){state.historyPast.push(clone(before));if(state.historyPast.length>100)state.historyPast.shift();state.historyFuture.length=0}const saved=await replaceDrawings(state.symbol,after);chart.setDrawings(saved);updateHistoryButtons()}
function updateHistoryButtons(){$("#undo").disabled=!state.historyPast.length;$("#redo").disabled=!state.historyFuture.length}
async function undo(){if(!state.historyPast.length)return;const current=clone(chart.drawings),next=state.historyPast.pop();state.historyFuture.push(current);await commitDrawings(current,next,{history:false})}
async function redo(){if(!state.historyFuture.length)return;const current=clone(chart.drawings),next=state.historyFuture.pop();state.historyPast.push(current);await commitDrawings(current,next,{history:false})}
function showDrawingMenu(drawing,point){const menu=$("#drawing-menu");if(!drawing){menu.hidden=true;return}menu.hidden=false;menu.dataset.type=drawing.type;$("#drawing-name").textContent={fib:"Fibonacci",long:"Long Position",trend:"Trend Line",dateRange:"Date Range",priceRange:"Price Range",text:"Text"}[drawing.type]||drawing.type;if(point&&innerWidth>700){menu.style.left=`${Math.max(8,Math.min(innerWidth-menu.offsetWidth-8,point.x))}px`;menu.style.top=`${Math.max(52,point.y-56)}px`}if(drawing.type==="trend"||drawing.type==="text"){$("#drawing-color").value=drawing.style?.color|| (drawing.type==="trend"?"#f23645":"#111111");$("#drawing-width").value=String(drawing.style?.lineWidth||2);$("#drawing-dash").value=drawing.style?.dash||"solid";$("#text-size").value=String(drawing.style?.fontSize||14)}}

function updateOhlc(row){if(!row){els.ohlc.textContent="";return}const d=row.close-row.open,p=row.open?d/row.open*100:0,kind=d>=0?"up":"down";els.ohlc.innerHTML=`<span class="${kind}">●</span> O${fmt(row.open)} H${fmt(row.high)} L${fmt(row.low)} C${fmt(row.close)} <span class="${kind}">${d>=0?"+":""}${fmt(d)} (${p.toFixed(2)}%)</span>`}
function fmt(v){return v>=1000?v.toLocaleString("en-US",{maximumFractionDigits:2}):v.toFixed(v>=1?4:6)}
async function load(replayTime=null){
  const token=`${state.symbol}:${state.timeframe}`;state.loading=true;state.stopStream?.();state.stopStream=null;setStatus("loading",Number.isFinite(replayTime)?"ĐANG TẢI REPLAY":"ĐANG TẢI");if(!Number.isFinite(replayTime))resetReplay();
  try{const params=Number.isFinite(replayTime)?{endTime:String(replayTime),limit:"1000"}:{};state.raw=await fetchKlines(state.symbol,currentTf(),params);if(token!==`${state.symbol}:${state.timeframe}`)return;if(Number.isFinite(replayTime)){const after=await fetchKlines(state.symbol,currentTf(),{startTime:String(replayTime+1),limit:"1000"});state.raw=mergeRows(state.raw,after)}state.rows=normalize(state.raw);void setMarketCache(token,state.raw);chart.offset=0;chart.setData(state.rows);chart.setDrawings(await listDrawings(state.symbol));if(Number.isFinite(replayTime)){state.replay.selecting=false;state.replay.active=true;state.replay.time=replayTime;state.replay.cut=Math.max(1,chart.nearestTime(replayTime));syncReplay()}else{startStream(token);setStatus("live","LIVE")}}
  catch(error){console.error(error);const cached=await getMarketCache(token);if(cached.length){state.raw=cached;state.rows=normalize(cached);chart.setData(state.rows);chart.setDrawings(await listDrawings(state.symbol));setStatus("offline","OFFLINE CACHE");toast("Đang dùng dữ liệu đã lưu trên thiết bị.")}else{setStatus("offline","LỖI DATA");toast("Không tải được Binance. Hãy kiểm tra mạng.")}}finally{state.loading=false}
}
function startStream(token){state.stopStream=marketStream(state.symbol,currentTf(),row=>{if(token!==`${state.symbol}:${state.timeframe}`||state.replay.active)return;state.raw=mergeRows(state.raw,[row]);state.rows=normalize(state.raw);void setMarketCache(token,state.raw);chart.setData(state.rows);updateOhlc(state.rows.at(-1))},kind=>setStatus(kind,kind==="live"?"LIVE":kind==="connecting"?"ĐANG NỐI":"MẤT KẾT NỐI"))}
async function loadOlder(){if(state.loadingOlder||!state.raw.length||state.replay.active)return;state.loadingOlder=true;const oldest=state.raw[0].time;try{const old=await fetchKlines(state.symbol,currentTf(),{endTime:String(oldest-1)});if(old.length){const keep=state.rows[Math.max(0,state.rows.length-chart.offset-chart.visibleBars)]?.time;state.raw=mergeRows(old,state.raw);state.rows=normalize(state.raw);chart.setData(state.rows);const keepIndex=chart.nearestTime(keep);chart.offset=Math.max(0,state.rows.length-chart.visibleBars-keepIndex);chart.render()}}finally{state.loadingOlder=false}}
function chooseSymbol(symbol){if(symbol===state.symbol)return;resetReplay();state.symbol=symbol;state.historyPast=[];state.historyFuture=[];updateHistoryButtons();els.symbol.value=symbol;updateUrl();void setSetting("lastSymbol",symbol);void load()}
function chooseTf(label){if(label===state.timeframe)return;const replayTime=state.replay.active?state.replay.time:null;state.timeframe=label;for(const b of els.tfs.children)b.classList.toggle("active",b.dataset.tf===label);void setSetting("timeframe",label);void load(replayTime)}
function syncReplay(animate=false){els.replay.classList.toggle("active",state.replay.active||state.replay.selecting);els.replay.setAttribute("aria-pressed",String(state.replay.active||state.replay.selecting));els.controls.hidden=!(state.replay.active||state.replay.selecting);els.countdown.hidden=state.replay.active||state.replay.selecting;if(state.replay.active)chart.setReplayCut(state.replay.cut,{animate});else if(!state.replay.selecting)chart.setReplayCut(null);setStatus(state.replay.active||state.replay.selecting?"offline":"live",state.replay.selecting?"CHỌN NẾN":state.replay.active?"REPLAY":"LIVE")}
function beginReplay(){clearInterval(state.replay.timer);state.replay.timer=null;state.replay.selecting=true;if(!state.replay.active)state.replay.cut=null;syncReplay();toast("Chạm vào nến muốn bắt đầu replay")}
async function stepReplay(){if(!state.replay.active)return;if(state.replay.cut>=state.rows.length){if(state.replay.loadingFuture||!state.raw.length)return;state.replay.loadingFuture=true;try{const newer=await fetchKlines(state.symbol,currentTf(),{startTime:String(state.raw.at(-1).time+1),limit:"1000"});if(newer.length){state.raw=mergeRows(state.raw,newer);state.rows=normalize(state.raw);chart.setData(state.rows)}}finally{state.replay.loadingFuture=false}}if(state.replay.cut<state.rows.length){state.replay.cut++;state.replay.time=state.rows[state.replay.cut]?.time||state.rows[state.replay.cut-1]?.time;syncReplay()}}
function playReplay(){if(state.replay.timer){clearInterval(state.replay.timer);state.replay.timer=null;$("#replay-play").textContent="▶";return}$("#replay-play").textContent="❚❚";state.replay.timer=setInterval(()=>void stepReplay().catch(error=>toast(error.message)),Math.max(60,900/state.replay.speed))}
function resetReplay(){clearInterval(state.replay.timer);Object.assign(state.replay,{selecting:false,active:false,cut:null,time:null,timer:null,loadingFuture:false});$("#replay-play").textContent="▶";els.countdown.hidden=false;chart.setReplayCut(null);els.controls.hidden=true;els.replay.classList.remove("active");els.replay.setAttribute("aria-pressed","false")}
function stopReplay(confirmExit=true){if(confirmExit&&(state.replay.active||state.replay.selecting)&&!confirm("Thoát Bar Replay và trở về dữ liệu LIVE?"))return false;resetReplay();return true}
async function replayAtDate(){const time=new Date($("#replay-date").value).getTime();if(!Number.isFinite(time))return;setStatus("loading","ĐANG TẢI REPLAY");try{const before=await fetchKlines(state.symbol,currentTf(),{endTime:String(time),limit:"1000"}),after=await fetchKlines(state.symbol,currentTf(),{startTime:String(time+1),limit:"1000"});state.raw=mergeRows(before,after);state.rows=normalize(state.raw);chart.setData(state.rows);state.replay.selecting=false;state.replay.active=true;state.replay.time=time;state.replay.cut=Math.max(1,chart.nearestTime(time));syncReplay(true)}catch(error){toast(error.message)}}
async function replayFirst(){try{const rows=await fetchKlines(state.symbol,currentTf(),{startTime:"0",limit:"1"});if(!rows.length)return;const d=new Date(rows[0].time),local=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);$("#replay-date").value=local;await replayAtDate()}catch(error){toast(error.message)}}
function updateCountdown(){if(state.replay.active||state.replay.selecting||!state.rows.length)return;const row=state.rows.at(-1),tf=currentTf();let end=row.closeTime+1;if(tf.biweekly)end=row.closeTime+1;if(tf.calendar){const d=new Date(row.time);end=Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1)}let s=Math.max(0,Math.ceil((end-Date.now())/1000)),d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600),m=Math.floor(s%3600/60),sec=s%60,p=n=>String(n).padStart(2,"0");els.countdown.textContent=`Đóng nến sau ${d?`${d}d `:""}${p(h)}:${p(m)}:${p(sec)}`}

async function init(){
  for(const s of ENABLED_SYMBOLS)els.symbol.add(new Option(s,s));
  for(const tf of TIMEFRAMES){const b=document.createElement("button");b.type="button";b.dataset.tf=tf.label;b.textContent=tf.label;b.onclick=()=>chooseTf(tf.label);els.tfs.append(b)}
  const remembered=await getSetting("lastSymbol"),savedTf=await getSetting("timeframe",DEFAULT_TIMEFRAME),savedBars=await getSetting("visibleBars",240),pricePercent=await getSetting("pricePercent",64),drawingDefaults=await getSetting("drawingDefaults",null);chart.setDefaults(drawingDefaults);document.querySelector(".price-pane").style.flex=String(Math.max(35,Math.min(80,+pricePercent||64)));document.querySelector(".rsi-pane").style.flex=String(100-Math.max(35,Math.min(80,+pricePercent||64)));state.symbol=resolveSymbol(location.search,remembered);state.timeframe=TIMEFRAMES.some(x=>x.label===savedTf)?savedTf:DEFAULT_TIMEFRAME;chart.visibleBars=Math.max(20,Math.min(1000,+savedBars||240));els.bars.value=chart.visibleBars;els.symbol.value=state.symbol;for(const b of els.tfs.children)b.classList.toggle("active",b.dataset.tf===state.timeframe);updateUrl();void setSetting("lastSymbol",state.symbol);
  els.symbol.onchange=()=>chooseSymbol(els.symbol.value);els.replay.onclick=beginReplay;$("#replay-step").onclick=()=>void stepReplay().catch(error=>toast(error.message));$("#replay-play").onclick=playReplay;$("#replay-exit").onclick=()=>{if(stopReplay(true))void load()};$("#replay-speed").onchange=e=>{state.replay.speed=+e.target.value;if(state.replay.timer){clearInterval(state.replay.timer);state.replay.timer=null;playReplay()}};$("#replay-date-go").onclick=()=>void replayAtDate();$("#replay-first").onclick=()=>void replayFirst();
  els.auth.onclick=async()=>{try{const cloud=await setupCloud();if(state.authUser){if(confirm("Đăng xuất khỏi đồng bộ ChartForge RSI?"))await cloud.signOut()}else await cloud.signIn()}catch(error){toast(error.code==="auth/unauthorized-domain"?"Hãy thêm domain này vào Firebase Authorized domains.":error.message)}};
  for(const b of document.querySelectorAll("[data-tool]"))b.onclick=()=>chart.setTool(b.dataset.tool);
  $("#snap").onclick=()=>{chart.setSnap(!chart.snap);$("#snap").classList.toggle("active",chart.snap);$("#snap").setAttribute("aria-pressed",String(chart.snap))};$("#clear").onclick=async()=>{if(confirm(`Xóa drawing của ${state.symbol}?`)){const before=clone(chart.drawings);await deleteDrawings(state.symbol);chart.setDrawings([]);state.historyPast.push(before);state.historyFuture=[];updateHistoryButtons()}};$("#undo").onclick=()=>void undo();$("#redo").onclick=()=>void redo();
  const updateStyle=async patch=>{const d=chart.selectedDrawing();if(!d)return;chart.defaults[d.type]={...(chart.defaults[d.type]||{}),...patch};void setSetting("drawingDefaults",chart.defaults);await chart.updateSelected({style:patch})};$("#delete-drawing").onclick=()=>void chart.removeSelected();$("#drawing-color").onchange=e=>void updateStyle({color:e.target.value});$("#drawing-width").onchange=e=>void updateStyle({lineWidth:+e.target.value});$("#drawing-dash").onchange=e=>void updateStyle({dash:e.target.value});$("#text-size").onchange=e=>void updateStyle({fontSize:+e.target.value});$("#edit-text").onclick=async()=>{const d=chart.selectedDrawing();if(!d)return;const text=prompt("Nội dung",d.text||"");if(text!=null)await chart.updateSelected({text})};
  $("#zoom-in").onclick=()=>{chart.visibleBars=Math.max(20,chart.visibleBars-20);els.bars.value=chart.visibleBars;chart.render();void setSetting("visibleBars",chart.visibleBars)};$("#zoom-out").onclick=()=>{chart.visibleBars=Math.min(1000,chart.visibleBars+20);els.bars.value=chart.visibleBars;chart.render();void setSetting("visibleBars",chart.visibleBars)};$("#reset").onclick=()=>{chart.resetView();els.bars.value=240;void setSetting("visibleBars",240)};
  addEventListener("keydown",e=>{const editing=e.target?.matches?.("input,textarea,select"),mod=e.ctrlKey||e.metaKey;if(editing||!mod)return;if(e.key.toLowerCase()==="z"){e.preventDefault();void(e.shiftKey?redo():undo())}else if(e.key.toLowerCase()==="y"){e.preventDefault();void redo()}});
  let timeDrag=null;document.querySelector(".bottom-bar").addEventListener("pointerdown",e=>{if(e.target.closest("button,input,select"))return;const rect=e.currentTarget.getBoundingClientRect();timeDrag={id:e.pointerId,x:e.clientX,bars:chart.visibleBars,offset:chart.offset,ratio:Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width))};e.currentTarget.setPointerCapture(e.pointerId)});document.querySelector(".bottom-bar").addEventListener("pointermove",e=>{if(timeDrag?.id===e.pointerId)chart.timeScaleGesture(timeDrag.bars,timeDrag.offset,timeDrag.x,e.clientX,timeDrag.ratio)});for(const type of["pointerup","pointercancel"])document.querySelector(".bottom-bar").addEventListener(type,()=>timeDrag=null);
  $("#export").onclick=async()=>{const data=await exportLocalData();if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download=`chartforge-rsi-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};$("#import-button").onclick=()=>$("#import-file").click();$("#import-file").onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const result=await importLocalData(JSON.parse(await file.text()));toast(`Đã nhập ${result.drawings} drawing`);chart.setDrawings(await listDrawings(state.symbol))}catch(error){toast(error.message)}finally{e.target.value=""}};
  let splitDrag=null;const splitter=document.querySelector(".splitter"),stack=document.querySelector(".chart-stack"),pricePane=document.querySelector(".price-pane"),rsiPane=document.querySelector(".rsi-pane");splitter.addEventListener("pointerdown",e=>{splitDrag=e.pointerId;splitter.setPointerCapture(e.pointerId)});splitter.addEventListener("pointermove",e=>{if(splitDrag!==e.pointerId)return;const rect=stack.getBoundingClientRect(),percent=Math.max(35,Math.min(80,(e.clientY-rect.top)/rect.height*100));pricePane.style.flex=String(percent);rsiPane.style.flex=String(100-percent);chart.render()});for(const type of["pointerup","pointercancel"])splitter.addEventListener(type,e=>{if(splitDrag!==e.pointerId)return;splitDrag=null;void setSetting("pricePercent",parseFloat(pricePane.style.flex))});
  await load();setInterval(updateCountdown,1000);void setupCloud().catch(()=>{});
  if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(console.warn);
  console.info(`ChartForge RSI PWA ${APP_VERSION}`)
}
void init();
