import{indicators,formatDuration,pointerAnchoredBounds,anchoredTimeScale}from"./math.js";
const GUTTER=70,PAD=8,clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),copy=value=>structuredClone(value);
const distanceToSegment=(p,a,b)=>{const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy||1,t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/l,0,1);return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)};
export class ChartView{
  constructor(price,rsi,events={}){this.canvases=[price,rsi];this.events=events;this.rows=[];this.allRows=[];this.ind={rsi:[],ema:[],wma:[]};this.visibleBars=240;this.offset=0;this.hover=null;this.tool=null;this.draft=null;this.drawings=[];this.selected=null;this.snap=false;this.shift=false;this.pointers=new Map();this.drag=null;this.manualBounds=null;this.animation=null;this.defaults={trend:{color:"#f23645",lineWidth:2,dash:"solid"},text:{color:"#111111",fontSize:14}};this.install();const shift=e=>{if(e.key!=="Shift")return;this.shift=e.type==="keydown";if(this.drag?.kind==="anchor")this.updateAnchor(this.drag.pointer);else if(this.draft)this.updateDraft(this.draft.pointer);this.render()};addEventListener("keydown",shift,true);addEventListener("keyup",shift,true);addEventListener("blur",()=>this.shift=false);new ResizeObserver(()=>this.render()).observe(price.parentElement)}
  setDefaults(defaults){this.defaults={trend:{...this.defaults.trend,...(defaults?.trend||{})},text:{...this.defaults.text,...(defaults?.text||{})}}}
  setData(rows){this.allRows=rows;this.rows=rows;this.ind=indicators(rows);this.offset=clamp(this.offset,-Math.round(this.visibleBars*.25),Math.max(0,rows.length-20));this.render()}
  setReplayCut(index,{animate=false}={}){const oldStart=this.range().start;this.rows=index==null?this.allRows:this.allRows.slice(0,index);this.ind=indicators(this.rows);if(index==null){this.offset=0;this.render();return}if(animate){this.offset=clamp(this.rows.length-(oldStart+this.visibleBars),-Math.round(this.visibleBars*.25),Math.max(0,this.rows.length-20));this.animateOffset(-Math.min(30,Math.round(this.visibleBars*.18)))}else{this.offset=clamp(this.offset,-Math.round(this.visibleBars*.25),Math.max(0,this.rows.length-20));this.render()}}
  animateOffset(target){cancelAnimationFrame(this.animation);const from=this.offset,start=performance.now(),duration=720,tick=now=>{const t=clamp((now-start)/duration,0,1),ease=t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;this.offset=from+(target-from)*ease;this.render();if(t<1)this.animation=requestAnimationFrame(tick)};this.animation=requestAnimationFrame(tick)}
  setDrawings(rows){this.drawings=rows||[];if(this.selected&&!this.drawings.some(x=>x.id===this.selected))this.select(null);this.render()}
  setTool(tool){this.tool=this.tool===tool?null:tool;this.draft=null;this.select(null);this.events.tool?.(this.tool);this.render()}
  setSnap(value){this.snap=!!value;if(this.drag?.kind==="anchor")this.updateAnchor(this.drag.pointer);else if(this.draft)this.updateDraft(this.draft.pointer);this.render()}
  select(id,point){this.selected=id;this.events.select?.(this.drawings.find(x=>x.id===id)||null,point);this.render()}
  selectedDrawing(){return this.drawings.find(x=>x.id===this.selected)||null}
  async removeSelected(){const before=copy(this.drawings),drawing=this.selectedDrawing();if(!drawing)return;this.drawings=this.drawings.filter(x=>x.id!==drawing.id);this.select(null);await this.events.change?.(before,copy(this.drawings));this.render()}
  async updateSelected(patch){const before=copy(this.drawings),index=this.drawings.findIndex(x=>x.id===this.selected);if(index<0)return;this.drawings[index]={...this.drawings[index],...patch,style:{...(this.drawings[index].style||{}),...(patch.style||{})}};await this.events.change?.(before,copy(this.drawings));this.events.select?.(this.drawings[index]);this.render()}
  range(){const end=Math.max(1,this.rows.length-this.offset),start=end-this.visibleBars;return{start,end}}
  geometry(canvas){const rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;if(canvas.width!==Math.round(rect.width*dpr)||canvas.height!==Math.round(rect.height*dpr)){canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr)}const ctx=canvas.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w:rect.width,h:rect.height,plotW:Math.max(1,rect.width-GUTTER),rect}}
  autoBounds(){const{start,end}=this.range(),seen=this.rows.slice(Math.max(0,Math.floor(start)),Math.min(this.rows.length,Math.ceil(end)));let lo=Math.min(...seen.map(x=>x.low)),hi=Math.max(...seen.map(x=>x.high));if(!Number.isFinite(lo)){lo=0;hi=1}const p=(hi-lo||1)*.08;return{lo:lo-p,hi:hi+p}}
  priceBounds(){return this.manualBounds||this.autoBounds()}
  xFor(index,g){return PAD+(index-this.range().start)/Math.max(1,this.visibleBars-1)*(g.plotW-PAD*2)}
  indexFloat(clientX,g){const ratio=(clientX-g.rect.left-PAD)/Math.max(1,g.plotW-PAD*2);return this.range().start+ratio*(this.visibleBars-1)}
  indexFor(clientX,g){return clamp(Math.round(this.indexFloat(clientX,g)),0,Math.max(0,this.rows.length-1))}
  priceFor(clientY,g,b=this.priceBounds()){const ratio=(clientY-g.rect.top-PAD)/Math.max(1,g.h-PAD*2);return b.hi-clamp(ratio,0,1)*(b.hi-b.lo)}
  rsiFor(clientY,g){return clamp(100-(clientY-g.rect.top)/Math.max(1,g.h)*100,0,100)}
  yFor(price,g,b=this.priceBounds()){return PAD+(b.hi-price)/(b.hi-b.lo)*Math.max(1,g.h-PAD*2)}
  timeForIndex(index){if(this.rows[index])return this.rows[index].time;if(!this.rows.length)return Date.now();const last=this.rows.length-1,step=last?this.rows[last].time-this.rows[last-1].time:3600000;return this.rows[last].time+(index-last)*step}
  nearestTime(time){let lo=0,hi=Math.max(0,this.rows.length-1);while(lo<hi){const m=(lo+hi)>>1;if(this.rows[m].time<time)lo=m+1;else hi=m}return lo}
  render(){this.renderPrice();this.renderRsi()}
  grid(ctx,w,h,plotW){ctx.clearRect(0,0,w,h);ctx.strokeStyle="#eceff3";ctx.lineWidth=1;for(let i=1;i<6;i++){ctx.beginPath();ctx.moveTo(0,i*h/6+.5);ctx.lineTo(plotW,i*h/6+.5);ctx.stroke()}for(let i=1;i<7;i++){ctx.beginPath();ctx.moveTo(i*plotW/7+.5,0);ctx.lineTo(i*plotW/7+.5,h);ctx.stroke()}ctx.strokeStyle="#d9dde3";ctx.beginPath();ctx.moveTo(plotW+.5,0);ctx.lineTo(plotW+.5,h);ctx.stroke()}
  renderPrice(){const g=this.geometry(this.canvases[0]),{ctx,w,h,plotW}=g,b=this.priceBounds(),{start,end}=this.range();this.grid(ctx,w,h,plotW);const slot=(plotW-PAD*2)/Math.max(1,this.visibleBars-1),body=Math.max(1,Math.min(11,slot*.65));for(let i=Math.max(0,Math.floor(start));i<Math.min(this.rows.length,Math.ceil(end));i++){const r=this.rows[i],x=this.xFor(i,g),yo=this.yFor(r.open,g,b),yc=this.yFor(r.close,g,b),yh=this.yFor(r.high,g,b),yl=this.yFor(r.low,g,b),color=r.close>=r.open?"#089981":"#f23645";ctx.strokeStyle=ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x,yh);ctx.lineTo(x,yl);ctx.stroke();ctx.fillRect(x-body/2,Math.min(yo,yc),body,Math.max(1,Math.abs(yc-yo)))}this.renderDrawings(ctx,g,b);for(let i=0;i<6;i++){const p=b.hi-(b.hi-b.lo)*i/5;ctx.fillStyle="#374151";ctx.font="10px Arial";ctx.textAlign="left";ctx.fillText(this.formatPrice(p),plotW+5,12+(h-20)*i/5)}this.renderHover(ctx,g,b,true)}
  renderRsi(){const g=this.geometry(this.canvases[1]),{ctx,w,h,plotW}=g,{start,end}=this.range();this.grid(ctx,w,h,plotW);ctx.fillStyle="#f3e8ff";ctx.fillRect(0,h*.3,plotW,h*.4);const line=(values,color,width=1.5)=>{ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=width;let began=false;for(let i=Math.max(0,Math.floor(start));i<Math.min(this.rows.length,Math.ceil(end));i++){const v=values[i];if(v==null)continue;const x=this.xFor(i,g),y=h-v/100*h;if(!began){ctx.moveTo(x,y);began=true}else ctx.lineTo(x,y)}ctx.stroke()};line(this.ind.rsi,"#b548c6",2);line(this.ind.ema,"#2e9f55");line(this.ind.wma,"#3b82f6");this.renderRsiDrawings(ctx,g);for(const v of[30,50,70]){ctx.fillStyle="#6b7280";ctx.font="10px Arial";ctx.fillText(String(v),plotW+7,h-v/100*h)}this.renderHover(ctx,g,null,false)}
  formatPrice(p){if(p>=1000)return p.toLocaleString("en-US",{maximumFractionDigits:2});if(p>=1)return p.toFixed(4);return p.toPrecision(5)}
  renderHover(ctx,g,b,price){if(this.hover==null||this.hover<this.range().start||this.hover>=this.range().end)return;const x=this.xFor(this.hover,g);ctx.save();ctx.setLineDash([5,5]);ctx.strokeStyle="#667085";ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,g.h);ctx.stroke();if(price&&this.rows[this.hover]){const y=this.yFor(this.rows[this.hover].close,g,b);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(g.plotW,y);ctx.stroke()}ctx.restore()}
  point(anchor,g,b){return{x:this.xFor(this.nearestTime(anchor.time),g),y:this.yFor(anchor.price,g,b)}}
  rsiPoint(anchor,g){return{x:this.xFor(this.nearestTime(anchor.time),g),y:g.h-clamp(anchor.price,0,100)/100*g.h}}
  anchors(d){return["a","b","c"].filter(k=>d[k]).map(k=>({key:k,value:d[k]}))}
  dash(ctx,style={}){ctx.strokeStyle=style.color||"#f23645";ctx.lineWidth=clamp(+style.lineWidth||2,1,8);ctx.setLineDash(style.dash==="dash"?[10,7]:style.dash==="dot"?[2,5]:[])}
  renderDrawings(ctx,g,b){for(const d of[...this.drawings,...(this.draft?[this.draft]:[])]){if(!d.a||d.pane==="rsi")continue;const a=this.point(d.a,g,b),z=d.b?this.point(d.b,g,b):a,selected=d.id===this.selected||d===this.draft;ctx.save();if(d.type==="trend"){this.dash(ctx,d.style);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(z.x,z.y);ctx.stroke()}else if(d.type==="fib"){for(const level of[0,.236,.382,.5,.618,.786,1]){const y=a.y+(z.y-a.y)*level;ctx.strokeStyle=level===.5?"#ec4899":"#6b7280";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(Math.min(a.x,z.x),y);ctx.lineTo(Math.max(a.x,z.x),y);ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.font="10px Arial";ctx.fillText(String(level),Math.min(a.x,z.x)+3,y-2)}}else if(d.type==="long"){const c=this.point(d.c||{time:d.b.time,price:d.a.price-(d.b.price-d.a.price)*.5},g,b),left=Math.min(a.x,z.x),right=Math.max(a.x,z.x);ctx.fillStyle="#22c55e33";ctx.fillRect(left,Math.min(a.y,z.y),right-left,Math.abs(z.y-a.y));ctx.fillStyle="#ef444433";ctx.fillRect(left,Math.min(a.y,c.y),right-left,Math.abs(c.y-a.y));ctx.strokeStyle="#6b7280";for(const y of[a.y,z.y,c.y]){ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke()}}else if(d.type==="text"){const size=clamp(+d.style?.fontSize||14,10,48);ctx.fillStyle=d.style?.color||"#111";ctx.font=`${size}px Arial`;ctx.fillText(d.text||"Text",a.x,a.y)}else{ctx.fillStyle=d.type==="dateRange"?"#ffb74d55":"#2962ff22";const left=Math.min(a.x,z.x),top=Math.min(a.y,z.y),width=Math.abs(z.x-a.x),height=Math.max(18,Math.abs(z.y-a.y));ctx.fillRect(left,top,width,height);ctx.strokeStyle="#2962ff";ctx.setLineDash([5,4]);ctx.strokeRect(left,top,width,height);ctx.setLineDash([]);ctx.fillStyle="#2962ff";ctx.font="bold 11px Arial";let label;if(d.type==="dateRange"){const ai=this.nearestTime(d.a.time),bi=this.nearestTime(d.b.time),from=Math.min(ai,bi),to=Math.max(ai,bi),volume=this.rows.slice(from,to+1).reduce((sum,row)=>sum+(row.volume||0),0),vol=volume>=1e6?`${(volume/1e6).toFixed(2)}M`:volume>=1e3?`${(volume/1e3).toFixed(2)}K`:volume.toFixed(2);label=`${to-from+1} bars, ${formatDuration(d.a.time,d.b.time)} · Vol ${vol}`}else label=`${((d.b.price-d.a.price)/d.a.price*100).toFixed(2)}%`;ctx.fillText(label,left+5,top-6)}if(selected)for(const{value}of this.anchors(d)){const p=this.point(value,g,b);ctx.fillStyle="#fff";ctx.strokeStyle="#2962ff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.restore()}}
  renderRsiDrawings(ctx,g){for(const d of[...this.drawings,...(this.draft?[this.draft]:[])]){if(d.type!=="trend"||d.pane!=="rsi"||!d.b)continue;const a=this.rsiPoint(d.a,g),b=this.rsiPoint(d.b,g);ctx.save();this.dash(ctx,d.style);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();if(d.id===this.selected||d===this.draft)for(const p of[a,b]){ctx.fillStyle="#fff";ctx.strokeStyle="#2962ff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.restore()}}
  hitTest(clientX,clientY,g,b,pane="price"){const p={x:clientX-g.rect.left,y:clientY-g.rect.top},point=a=>pane==="rsi"?this.rsiPoint(a,g):this.point(a,g,b),eligible=d=>(d.pane||"price")===pane;for(let i=this.drawings.length-1;i>=0;i--){const d=this.drawings[i];if(!eligible(d))continue;for(const anchor of this.anchors(d)){const q=point(anchor.value);if(Math.hypot(p.x-q.x,p.y-q.y)<=14)return{drawing:d,anchor:anchor.key}}}for(let i=this.drawings.length-1;i>=0;i--){const d=this.drawings[i];if(!eligible(d))continue;const a=point(d.a),z=d.b?point(d.b):a;if(d.type==="trend"&&distanceToSegment(p,a,z)<=10)return{drawing:d};if(d.type==="text"&&p.x>=a.x-8&&p.x<=a.x+160&&p.y>=a.y-12&&p.y<=a.y+40)return{drawing:d};if(d.b&&p.x>=Math.min(a.x,z.x)-8&&p.x<=Math.max(a.x,z.x)+8&&p.y>=Math.min(a.y,z.y)-12&&p.y<=Math.max(a.y,z.y)+20)return{drawing:d}}return null}
  install(){for(const canvas of this.canvases){canvas.addEventListener("pointerdown",e=>this.down(e,canvas));canvas.addEventListener("pointermove",e=>this.move(e,canvas));canvas.addEventListener("pointerup",e=>this.up(e));canvas.addEventListener("pointercancel",e=>this.up(e));canvas.addEventListener("dblclick",e=>this.doubleClick(e,canvas));canvas.addEventListener("pointerleave",()=>{if(!this.drag){this.hover=null;this.events.hover?.(null);this.render()}});canvas.addEventListener("wheel",e=>{e.preventDefault();const g=this.geometry(canvas),anchor=this.indexFloat(e.clientX,g),oldStart=this.range().start,ratio=(anchor-oldStart)/Math.max(1,this.visibleBars-1);this.visibleBars=clamp(Math.round(this.visibleBars*Math.exp(e.deltaY*.0015)),20,1000);const newStart=anchor-ratio*(this.visibleBars-1);this.offset=clamp(this.rows.length-(newStart+this.visibleBars),-Math.round(this.visibleBars*.25),Math.max(0,this.rows.length-20));this.events.zoom?.(this.visibleBars);this.render()},{passive:false})}}
  async down(e,canvas){canvas.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const g=this.geometry(canvas),index=this.indexFor(e.clientX,g),pane=canvas===this.canvases[1]?"rsi":"price",value=pane==="rsi"?this.rsiFor(e.clientY,g):this.priceFor(e.clientY,g);this.hover=index;this.events.hover?.(this.rows[index]||null);if(pane==="price"&&e.clientX-g.rect.left>=g.plotW){const bounds=this.priceBounds(),ratio=clamp((e.clientY-g.rect.top-PAD)/Math.max(1,g.h-PAD*2),0,1);this.drag={kind:"priceScale",y:e.clientY,bounds:{...bounds},pivot:this.priceFor(e.clientY,g,bounds),ratio};return}if(this.events.selectReplay?.(index))return;if(this.tool&&(pane==="price"||(pane==="rsi"&&this.tool==="trend"))){const a={time:this.timeForIndex(index),price:value};if(this.tool==="text"){const text=await this.events.text?.("Text");if(!text)return;const drawing={id:crypto.randomUUID(),symbol:this.events.symbol?.(),type:"text",a,text,style:{...this.defaults.text}},before=copy(this.drawings);this.drawings.push(drawing);await this.events.change?.(before,copy(this.drawings));this.tool=null;this.events.tool?.(null);this.select(drawing.id,{x:e.clientX,y:e.clientY});return}this.draft={id:crypto.randomUUID(),symbol:this.events.symbol?.(),type:this.tool,pane,a,b:{...a},pointer:{x:e.clientX,y:e.clientY},style:this.tool==="trend"?{...this.defaults.trend}:undefined};if(this.tool==="long")this.draft.c={...a};this.drag={kind:"draw",canvas,pane};this.render();return}const hit=this.hitTest(e.clientX,e.clientY,g,this.priceBounds(),pane);if(hit){const before=copy(this.drawings),drawing=this.drawings.find(x=>x.id===hit.drawing.id);this.select(drawing.id,{x:e.clientX,y:e.clientY});this.drag={kind:hit.anchor?"anchor":"drawing",drawing,anchor:hit.anchor,before,pointer:{x:e.clientX,y:e.clientY},startIndex:index,startValue:value,original:copy(drawing),canvas,pane};return}else if(pane==="price")this.select(null);this.drag={kind:"pan",canvas,pane,x:e.clientX,y:e.clientY,offset:this.offset,bounds:{...this.priceBounds()}};if(this.pointers.size===2){const pts=[...this.pointers.values()];this.drag={kind:"pinch",distance:Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y),bars:this.visibleBars,offset:this.offset}}}
  move(e,canvas){const g=this.geometry(canvas),index=this.indexFor(e.clientX,g);this.hover=index;this.events.hover?.(this.rows[index]||null);if(this.pointers.has(e.pointerId))this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(!this.drag){this.render();return}if(this.drag.kind==="draw"){this.updateDraft({x:e.clientX,y:e.clientY});this.render()}else if(this.drag.kind==="anchor"){this.updateAnchor({x:e.clientX,y:e.clientY});this.render()}else if(this.drag.kind==="drawing"){const value=this.drag.pane==="rsi"?this.rsiFor(e.clientY,g):this.priceFor(e.clientY,g),di=index-this.drag.startIndex,dp=value-this.drag.startValue,d=this.drag.drawing;for(const key of["a","b","c"])if(this.drag.original[key])d[key]={time:this.timeForIndex(this.nearestTime(this.drag.original[key].time)+di),price:this.drag.original[key].price+dp};this.render()}else if(this.drag.kind==="priceScale"){this.manualBounds=pointerAnchoredBounds(this.drag.bounds,this.drag.pivot,this.drag.ratio,e.clientY-this.drag.y);this.render()}else if(this.pointers.size>=2){const pts=[...this.pointers.values()],distance=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y);if(this.drag.kind!=="pinch")this.drag={kind:"pinch",distance,bars:this.visibleBars,offset:this.offset};this.visibleBars=clamp(Math.round(this.drag.bars*this.drag.distance/Math.max(1,distance)),20,1000);this.events.zoom?.(this.visibleBars);this.render()}else if(this.drag.kind==="pan"){const slots=(g.plotW-PAD*2)/Math.max(1,this.visibleBars-1);this.offset=clamp(this.drag.offset+(e.clientX-this.drag.x)/slots,-Math.round(this.visibleBars*.25),Math.max(0,this.rows.length-20));if(this.drag.pane==="price"){const shift=(e.clientY-this.drag.y)/Math.max(1,g.h)*(this.drag.bounds.hi-this.drag.bounds.lo);this.manualBounds={lo:this.drag.bounds.lo+shift,hi:this.drag.bounds.hi+shift}}if(this.offset>=this.rows.length-this.visibleBars-3)this.events.older?.();this.render()}}
  updateDraft(pointer){if(!this.draft||!pointer)return;const g=this.geometry(this.drag?.canvas||this.canvases[0]),index=this.indexFor(pointer.x,g),value=this.draft.pane==="rsi"?this.rsiFor(pointer.y,g):this.priceFor(pointer.y,g),raw={time:this.timeForIndex(index),price:value},otherY=this.draft.pane==="rsi"?g.h-this.draft.a.price/100*g.h:this.yFor(this.draft.a.price,g);if(this.draft.type==="trend"&&(this.snap||this.shift)){const a=this.draft.a,dx=Math.abs(index-this.nearestTime(a.time)),dy=Math.abs(pointer.y-otherY);this.draft.b=dx*2>dy?{time:raw.time,price:a.price}:{time:a.time,price:raw.price}}else this.draft.b=raw;if(this.draft.type==="long")this.draft.c={time:raw.time,price:this.draft.a.price-(raw.price-this.draft.a.price)*.5};this.draft.pointer=pointer}
  updateAnchor(pointer){if(!this.drag?.drawing||!pointer)return;const g=this.geometry(this.drag.canvas||this.canvases[0]),index=this.indexFor(pointer.x,g),value=this.drag.pane==="rsi"?this.rsiFor(pointer.y,g):this.priceFor(pointer.y,g),raw={time:this.timeForIndex(index),price:value},d=this.drag.drawing,key=this.drag.anchor;if(d.type==="trend"&&(this.snap||this.shift)&&["a","b"].includes(key)){const other=key==="a"?d.b:d.a,otherY=this.drag.pane==="rsi"?g.h-other.price/100*g.h:this.yFor(other.price,g),dx=Math.abs(index-this.nearestTime(other.time)),dy=Math.abs(pointer.y-otherY);d[key]=dx*2>dy?{time:raw.time,price:other.price}:{time:other.time,price:raw.price}}else d[key]=raw;this.drag.pointer=pointer}
  async up(e){this.pointers.delete(e.pointerId);if(this.drag?.kind==="draw"&&this.draft){const before=copy(this.drawings),done=this.draft;this.draft=null;this.drawings.push(done);await this.events.change?.(before,copy(this.drawings));this.tool=null;this.events.tool?.(null);this.select(done.id,{x:e.clientX,y:e.clientY})}else if(["anchor","drawing"].includes(this.drag?.kind))await this.events.change?.(this.drag.before,copy(this.drawings));this.drag=null;this.render()}
  async doubleClick(e,canvas){if(canvas!==this.canvases[0])return;const g=this.geometry(canvas),hit=this.hitTest(e.clientX,e.clientY,g,this.priceBounds());if(hit?.drawing.type==="text"){const text=await this.events.text?.(hit.drawing.text);if(text!=null&&text!==hit.drawing.text){this.select(hit.drawing.id);await this.updateSelected({text})}}}
  resetView(){this.visibleBars=240;this.offset=0;this.manualBounds=null;this.render()}
  timeScaleGesture(startBars,startOffset,startX,currentX,ratio=.5){const next=anchoredTimeScale(this.rows.length,startBars,startOffset,currentX-startX,ratio);this.visibleBars=next.bars;this.offset=clamp(next.offset,-Math.round(this.visibleBars*.25),Math.max(0,this.rows.length-20));this.events.zoom?.(this.visibleBars);this.render()}
}
