import{ENABLED_SYMBOLS}from"./config.js";
const DB_NAME="chartforge-rsi",DB_VERSION=1,STORES=["settings","drawings","syncQueue","marketCache","meta"],DRAWING_TYPES=new Set(["fib","long","priceRange","dateRange","trend","text"]);
let dbPromise;
export function openDatabase(){
  if(!globalThis.indexedDB)return Promise.resolve(null);
  return dbPromise ||= new Promise((resolve,reject)=>{let settled=false;const finish=value=>{if(!settled){settled=true;resolve(value)}},timer=setTimeout(()=>finish(null),1500),req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;for(const name of STORES)if(!db.objectStoreNames.contains(name))db.createObjectStore(name,{keyPath:"id"})};req.onsuccess=()=>{clearTimeout(timer);finish(req.result)};req.onerror=()=>{clearTimeout(timer);if(!settled)reject(req.error)}});
}
async function request(store,mode,action){const db=await openDatabase();if(!db)return null;return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode),os=tx.objectStore(store),req=action(os);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function getAll(store){return await request(store,"readonly",s=>s.getAll())||[]}
export async function getSetting(id,fallback=null){const row=await request("settings","readonly",s=>s.get(id));if(row)return row.value;try{const value=localStorage.getItem(`cfrsi:${id}`);return value==null?fallback:JSON.parse(value)}catch{return fallback}}
export async function setSetting(id,value,{remote=false}={}){try{localStorage.setItem(`cfrsi:${id}`,JSON.stringify(value))}catch{}const existing=await request("settings","readonly",s=>s.get(id)),row={id,value,revision:(existing?.revision||0)+(remote?0:1),updatedAt:Date.now(),deviceId:await deviceId()};await request("settings","readwrite",s=>s.put(row));if(!remote)await queueMutation("setting",row);return value}
export async function listSettingRows(){return getAll("settings")}
export async function listDrawings(symbol,{includeDeleted=false}={}){const all=await getAll("drawings");return all.filter(x=>(!symbol||x.symbol===symbol)&&(includeDeleted||!x.deleted))}
export async function getDrawing(id){return request("drawings","readonly",s=>s.get(id))}
export async function putDrawing(drawing,{remote=false}={}){const id=drawing.id||crypto.randomUUID(),existing=await getDrawing(id),value=remote?{...drawing,id}:{...drawing,id,revision:Math.max(drawing.revision||0,existing?.revision||0)+1,updatedAt:Date.now(),deviceId:await deviceId(),deleted:false};await request("drawings","readwrite",s=>s.put(value));if(!remote)await queueMutation("drawing",value);return value}
export async function deleteDrawing(drawing){const existing=await getDrawing(drawing.id),tombstone={...(existing||drawing),deleted:true,revision:Math.max(drawing.revision||0,existing?.revision||0)+1,updatedAt:Date.now(),deviceId:await deviceId()};await request("drawings","readwrite",s=>s.put(tombstone));await queueMutation("drawing",tombstone);return tombstone}
export async function deleteDrawings(symbol){const rows=await listDrawings(symbol);for(const row of rows)await deleteDrawing(row)}
export async function replaceDrawings(symbol,next){const current=await listDrawings(symbol),byId=new Map(current.map(x=>[x.id,x])),ids=new Set(next.map(x=>x.id));for(const row of current)if(!ids.has(row.id))await deleteDrawing(row);const saved=[];for(const row of next){const revision=Math.max(row.revision||0,byId.get(row.id)?.revision||0);saved.push(await putDrawing({...row,symbol,revision}))}return saved}
export async function applyRemoteSetting(row){const existing=await request("settings","readonly",s=>s.get(row.id));if(existing&&compareVersions(existing,row)>=0)return false;try{localStorage.setItem(`cfrsi:${row.id}`,JSON.stringify(row.value))}catch{}await request("settings","readwrite",s=>s.put(row));return true}
export async function applyRemoteDrawing(row){const{serverUpdatedAt,...clean}=row,existing=await getDrawing(clean.id);if(existing&&compareVersions(existing,clean)>=0)return false;await putDrawing(clean,{remote:true});return true}
export function compareVersions(a,b){const ar=Number(a?.revision)||0,br=Number(b?.revision)||0;if(ar!==br)return ar-br;const at=Number(a?.updatedAt)||0,bt=Number(b?.updatedAt)||0;if(at!==bt)return at-bt;return String(a?.deviceId||"").localeCompare(String(b?.deviceId||""))}
export async function getMarketCache(id){return(await request("marketCache","readonly",s=>s.get(id)))?.rows||[]}
export async function setMarketCache(id,rows){const bounded=(rows||[]).slice(-3000);return request("marketCache","readwrite",s=>s.put({id,rows:bounded,updatedAt:Date.now()}))}
export async function deviceId(){let id=await request("meta","readonly",s=>s.get("deviceId"));if(id)return id.value;id={id:"deviceId",value:crypto.randomUUID()};await request("meta","readwrite",s=>s.put(id));return id.value}
export async function switchCloudUser(uid){const current=await request("meta","readonly",s=>s.get("cloudUid"));if(!current){await request("meta","readwrite",s=>s.put({id:"cloudUid",value:uid}));return false}if(current.value===uid)return false;const db=await openDatabase();if(!db)return false;await new Promise((resolve,reject)=>{const tx=db.transaction(["settings","drawings","syncQueue","meta"],"readwrite");tx.objectStore("settings").clear();tx.objectStore("drawings").clear();tx.objectStore("syncQueue").clear();tx.objectStore("meta").put({id:"cloudUid",value:uid});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)});for(const key of["lastSymbol","timeframe","visibleBars","pricePercent","drawingDefaults"])try{localStorage.removeItem(`cfrsi:${key}`)}catch{}return true}
async function queueMutation(kind,payload){const result=await request("syncQueue","readwrite",s=>s.put({id:`${kind}:${payload.id}:${payload.revision}`,kind,payload,attempts:0,createdAt:Date.now()}));globalThis.dispatchEvent?.(new Event("cfrsi:local-change"));return result}
export async function listSyncQueue(){return getAll("syncQueue")}
export async function removeSyncQueue(ids){if(!ids?.length)return;const db=await openDatabase();if(!db)return;await new Promise((resolve,reject)=>{const tx=db.transaction("syncQueue","readwrite"),store=tx.objectStore("syncQueue");for(const id of ids)store.delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
export async function enqueueLocalSnapshot(){for(const row of await listSettingRows())await queueMutation("setting",row);for(const row of await listDrawings(null,{includeDeleted:true}))await queueMutation("drawing",row)}
export async function exportLocalData(){const db=await openDatabase();if(!db)return null;return{format:"chartforge-rsi",version:1,exportedAt:new Date().toISOString(),settings:await getAll("settings"),drawings:await getAll("drawings")}}
export async function importLocalData(payload){if(!payload||payload.format!=="chartforge-rsi"||payload.version!==1||!Array.isArray(payload.settings)||!Array.isArray(payload.drawings))throw new Error("File backup không hợp lệ");for(const row of payload.settings)if(!row||typeof row.id!=="string")throw new Error("Backup chứa setting không hợp lệ");for(const row of payload.drawings)if(!row||typeof row.id!=="string"||!ENABLED_SYMBOLS.includes(row.symbol)||!DRAWING_TYPES.has(row.type)||!row.a||!Number.isFinite(row.a.time)||!Number.isFinite(row.a.price))throw new Error("Backup chứa drawing không hợp lệ");const db=await openDatabase();if(!db)throw new Error("IndexedDB không khả dụng");await new Promise((resolve,reject)=>{const tx=db.transaction(["settings","drawings","syncQueue"],"readwrite"),settings=tx.objectStore("settings"),drawings=tx.objectStore("drawings"),queue=tx.objectStore("syncQueue");for(const row of payload.settings){settings.put(row);queue.put({id:`setting:${row.id}:${row.revision||0}`,kind:"setting",payload:row,attempts:0,createdAt:Date.now()})}for(const row of payload.drawings){drawings.put(row);queue.put({id:`drawing:${row.id}:${row.revision||0}`,kind:"drawing",payload:row,attempts:0,createdAt:Date.now()})}tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)});return{settings:payload.settings.length,drawings:payload.drawings.length}}
export const SCHEMA={name:DB_NAME,version:DB_VERSION,stores:STORES};
