import{chromium}from"playwright-core";

const base=process.argv[2]||"http://127.0.0.1:4173/",executablePath=process.env.CHARTFORGE_CHROME||"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",browser=await chromium.launch({executablePath,headless:true});
const readSettings=page=>page.evaluate(()=>new Promise((resolve,reject)=>{const open=indexedDB.open("chartforge-rsi",1);open.onerror=()=>reject(open.error);open.onsuccess=()=>{const get=open.result.transaction("settings","readonly").objectStore("settings").getAll();get.onerror=()=>reject(get.error);get.onsuccess=()=>resolve(Object.fromEntries(get.result.map(row=>[row.id,row.value])))}}));
const timeAxisRect=page=>page.evaluate(()=>{const rect=document.querySelector("#binance-rsi-mtf-host").shadowRoot.querySelector(".rsi-canvas").getBoundingClientRect();return{left:rect.left+8,right:rect.right-74,width:rect.width-82,y:rect.bottom-10}});
const expectedAxisZoom=(startZoom,startX,pointerX,axis)=>Math.max(20,Math.min(1000,Math.round(1+(startZoom-1)*(axis.right-startX)/(axis.right-pointerX))));
try{
  for(const symbol of["BTCUSDT","ETHUSDT","DOGEUSDT"]){
    const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];
    page.on("pageerror",error=>errors.push(error.message));
    await page.goto(`${base}?symbol=${symbol}`,{waitUntil:"domcontentloaded"});
    await page.waitForFunction(expected=>document.title.includes(`| ${expected} | ChartForge RSI`),symbol,{timeout:30000});
    await page.waitForFunction(()=>document.querySelector("#binance-rsi-mtf-host")?.shadowRoot?.querySelector(".status")?.dataset.state==="live",null,{timeout:30000});
    if(errors.length)throw new Error(`${symbol} runtime errors: ${errors.join("; ")}`);
    console.log(`${symbol}: ${await page.title()}`);await page.close();
  }
  for(const [width,height] of[[1280,800],[591,900],[390,700],[320,568]]){
    const page=await browser.newPage({viewport:{width,height}});await page.goto(`${base}?symbol=BTCUSDT`,{waitUntil:"domcontentloaded"});
    const layout=await page.waitForFunction(()=>{const shadow=document.querySelector("#binance-rsi-mtf-host")?.shadowRoot,status=shadow?.querySelector(".status"),auth=shadow?.querySelector(".pwa-auth"),topbar=shadow?.querySelector(".topbar");if(!status||!auth)return null;const s=status.getBoundingClientRect(),a=auth.getBoundingClientRect(),t=topbar.getBoundingClientRect();return{order:[...topbar.children].indexOf(status)<[...topbar.children].indexOf(auth),separated:s.right<=a.left,right:a.right<=t.right+1,visible:s.width>0&&a.width>0}},null,{timeout:30000}).then(handle=>handle.jsonValue());
    if(!layout.order||!layout.separated||!layout.right||!layout.visible)throw new Error(`${width}px layout failed: ${JSON.stringify(layout)}`);
    await page.waitForFunction(()=>document.querySelector("#binance-rsi-mtf-host")?.shadowRoot?.querySelector(".status")?.dataset.state==="live",null,{timeout:30000});
    const splitter=await page.evaluate(()=>{const rect=document.querySelector("#binance-rsi-mtf-host").shadowRoot.querySelector(".splitter").getBoundingClientRect();return{x:rect.left+rect.width/2,y:rect.top+rect.height/2}});
    await page.mouse.move(splitter.x,splitter.y);await page.mouse.down();await page.mouse.move(splitter.x,height-45,{steps:5});await page.mouse.up();await page.waitForTimeout(50);
    const panes=await page.evaluate(()=>{const shadow=document.querySelector("#binance-rsi-mtf-host").shadowRoot,panel=shadow.querySelector(".panel"),workspace=shadow.querySelector(".chart-workspace"),topbar=shadow.querySelector(".topbar"),bottom=shadow.querySelector(".bottom-bar"),price=shadow.querySelector(".price-canvas"),rsi=shadow.querySelector(".rsi-canvas"),rail=shadow.querySelector(".drawing-tools"),values=shadow.querySelector(".values"),countdown=shadow.querySelector(".candle-countdown"),legend=shadow.querySelector(".price-legend"),rect=element=>element.getBoundingClientRect(),p=rect(panel),w=rect(workspace),t=rect(topbar),b=rect(bottom),pc=rect(price),rc=rect(rsi),rr=rect(rail),vr=rect(values),cr=rect(countdown),lr=rect(legend),legendLines=new Set([...legend.children].map(node=>Math.round(node.getBoundingClientRect().top))).size,hit=shadow.elementFromPoint(b.left+b.width/2,b.top+b.height/2),order=[...rail.children].map(node=>node.className),bottomStyle=getComputedStyle(bottom),legendStyle=getComputedStyle(legend);return{panelBottom:p.bottom,workspaceTop:w.top,workspaceBottom:w.bottom,topbarBottom:t.bottom,bottomTop:b.top,bottomBottom:b.bottom,bottomBorder:[bottomStyle.borderTopWidth,bottomStyle.borderTopStyle,bottomStyle.borderTopColor],priceBottom:pc.bottom,rsiBottom:rc.bottom,bottomHit:!!hit?.closest?.(".bottom-bar"),priceBacking:[price.width,Math.round(pc.width*devicePixelRatio),price.height,Math.round(pc.height*devicePixelRatio)],rsiBacking:[rsi.width,Math.round(rc.width*devicePixelRatio),rsi.height,Math.round(rc.height*devicePixelRatio)],railOrder:order,railScrolls:rail.scrollHeight>rail.clientHeight+1,countdownText:countdown.textContent,countdownInside:rr.left<=cr.left&&cr.right<=rr.right+1,valuesAtLeft:vr.left<=b.left+12,legendLines,legendInside:lr.left>=pc.left-1&&lr.right<=pc.right-73,legendOverflow:legend.scrollWidth>legend.clientWidth+1,legendPointer:legendStyle.pointerEvents}});
    if(panes.bottomBottom>panes.panelBottom+1||panes.workspaceTop<panes.topbarBottom-1||panes.workspaceBottom>panes.bottomTop+1||panes.priceBottom>panes.workspaceBottom+1||panes.rsiBottom>panes.workspaceBottom+1||!panes.bottomHit||panes.priceBacking[0]!==panes.priceBacking[1]||panes.priceBacking[2]!==panes.priceBacking[3]||panes.rsiBacking[0]!==panes.rsiBacking[1]||panes.rsiBacking[2]!==panes.rsiBacking[3])throw new Error(`${width}x${height} fixed-bar layout failed: ${JSON.stringify(panes)}`);
    const tail=panes.railOrder.slice(-5).join(" ");if(!tail.includes("undo-drawing")||!tail.includes("redo-drawing")||!tail.includes("clear-drawings")||!tail.includes("countdown-separator")||!tail.includes("candle-countdown"))throw new Error(`${width}x${height} drawing rail order failed: ${JSON.stringify(panes.railOrder)}`);
    if(!panes.countdownInside||/Đóng nến sau/.test(panes.countdownText)||!panes.valuesAtLeft)throw new Error(`${width}x${height} rail/bottom values layout failed: ${JSON.stringify(panes)}`);
    if(panes.bottomBorder[0]!=="1px"||panes.bottomBorder[1]!=="solid"||!panes.legendInside||panes.legendOverflow||panes.legendPointer!=="none"||(width<=390&&panes.legendLines<2)||(width>=1280&&panes.legendLines!==1))throw new Error(`${width}x${height} separator/OHLC layout failed: ${JSON.stringify(panes)}`);
    if(width<=700&&height>=568&&panes.railScrolls)throw new Error(`${width}x${height} compact drawing rail should fit without scrolling: ${JSON.stringify(panes)}`);
    if(width===1280){
      await page.evaluate(()=>{window.__nativeConfirmCalls=0;window.confirm=()=>{window.__nativeConfirmCalls++;return false};const shadow=document.querySelector("#binance-rsi-mtf-host").shadowRoot;shadow.querySelector(".trend-tool").click()});
      const drawingPoints=await page.evaluate(()=>{const rect=document.querySelector("#binance-rsi-mtf-host").shadowRoot.querySelector(".price-canvas").getBoundingClientRect();return{a:{x:rect.left+160,y:rect.top+120},b:{x:rect.left+280,y:rect.top+180}}});
      await page.mouse.move(drawingPoints.a.x,drawingPoints.a.y);await page.mouse.down();await page.mouse.move(drawingPoints.b.x,drawingPoints.b.y,{steps:3});await page.mouse.up();
      const drawingCount=()=>page.evaluate(()=>new Promise((resolve,reject)=>{const request=indexedDB.open("chartforge-rsi",1);request.onerror=()=>reject(request.error);request.onsuccess=()=>{const tx=request.result.transaction("drawings","readonly"),get=tx.objectStore("drawings").getAll();get.onerror=()=>reject(get.error);get.onsuccess=()=>resolve(get.result.filter(row=>row.symbol==="BTCUSDT"&&!row.deleted).length)}}));
      await page.waitForFunction(()=>{const shadow=document.querySelector("#binance-rsi-mtf-host").shadowRoot;return shadow.querySelector(".drawing-menu").classList.contains("show")});
      await page.waitForTimeout(120);const beforeCancel=await drawingCount();
      const opened=await page.evaluate(()=>{const shadow=document.querySelector("#binance-rsi-mtf-host").shadowRoot;shadow.querySelector(".clear-drawings").click();const dialog=shadow.querySelector(".confirm-dialog");return{show:dialog.classList.contains("show"),title:dialog.querySelector(".confirm-dialog-title").textContent,focused:shadow.activeElement?.classList.contains("confirm-dialog-cancel")}});await page.waitForTimeout(30);
      if(!opened.show||opened.title!=="Xóa tất cả drawing?")throw new Error(`Trash dialog did not open: ${JSON.stringify(opened)}`);
      await page.evaluate(()=>document.querySelector("#binance-rsi-mtf-host").shadowRoot.querySelector(".confirm-dialog-cancel").click());await page.waitForTimeout(120);
      const afterCancel=await drawingCount(),cancelState=await page.evaluate(()=>{const shadow=document.querySelector("#binance-rsi-mtf-host").shadowRoot;return{show:shadow.querySelector(".confirm-dialog").classList.contains("show"),nativeCalls:window.__nativeConfirmCalls,focusReturned:shadow.activeElement?.classList.contains("clear-drawings")}});
      if(afterCancel!==beforeCancel||cancelState.show||cancelState.nativeCalls||!cancelState.focusReturned)throw new Error(`Trash cancel mutated state: ${JSON.stringify({beforeCancel,afterCancel,cancelState})}`);
      await page.evaluate(()=>{const shadow=document.querySelector("#binance-rsi-mtf-host").shadowRoot;shadow.querySelector(".clear-drawings").click();const button=shadow.querySelector(".confirm-dialog-confirm");button.click();button.click()});await page.waitForTimeout(180);
      const afterConfirm=await drawingCount(),confirmState=await page.evaluate(()=>({nativeCalls:window.__nativeConfirmCalls,undoEnabled:!document.querySelector("#binance-rsi-mtf-host").shadowRoot.querySelector(".undo-drawing").disabled}));
      if(afterConfirm!==0||confirmState.nativeCalls||!confirmState.undoEnabled)throw new Error(`Trash confirm failed: ${JSON.stringify({afterConfirm,confirmState})}`);
      await page.evaluate(()=>document.querySelector("#binance-rsi-mtf-host").shadowRoot.querySelector(".undo-drawing").click());await page.waitForTimeout(180);const afterUndo=await drawingCount();if(afterUndo!==beforeCancel)throw new Error(`Trash undo failed: ${JSON.stringify({beforeCancel,afterUndo})}`);
    }
    const replayCountdown=await page.evaluate(()=>{const shadow=document.querySelector("#binance-rsi-mtf-host").shadowRoot;shadow.querySelector(".replay-button").click();return{countdownHidden:shadow.querySelector(".candle-countdown").classList.contains("hidden"),separatorHidden:shadow.querySelector(".countdown-separator").classList.contains("hidden")}});if(!replayCountdown.countdownHidden||!replayCountdown.separatorHidden)throw new Error(`${width}x${height} Replay countdown visibility failed: ${JSON.stringify(replayCountdown)}`);await page.evaluate(()=>{const shadow=document.querySelector("#binance-rsi-mtf-host").shadowRoot;shadow.querySelector(".replay-close").click();shadow.querySelector(".replay-exit-confirm").click()});
    if(width===591){await page.setViewportSize({width,height:720});await page.waitForTimeout(50);const dynamic=await page.evaluate(()=>{const shadow=document.querySelector("#binance-rsi-mtf-host").shadowRoot,panel=shadow.querySelector(".panel").getBoundingClientRect(),bottom=shadow.querySelector(".bottom-bar").getBoundingClientRect();return{viewport:visualViewport.height,panelBottom:panel.bottom,bottomBottom:bottom.bottom}});if(dynamic.panelBottom>dynamic.viewport+1||dynamic.bottomBottom>dynamic.panelBottom+1)throw new Error(`dynamic viewport layout failed: ${JSON.stringify(dynamic)}`)}
    console.log(`${width}x${height}: bottom bar fixed, panes clipped to workspace`);await page.close();
  }
  {
    const context=await browser.newContext({viewport:{width:1280,height:800},serviceWorkers:"block"}),page=await context.newPage();await page.goto(`${base}?symbol=BTCUSDT`,{waitUntil:"domcontentloaded"});await page.waitForFunction(()=>document.querySelector("#binance-rsi-mtf-host")?.shadowRoot?.querySelector(".status")?.dataset.state==="live",null,{timeout:30000});
    const axis=await timeAxisRect(page),startX=axis.left+axis.width*.43,pointerX=startX+300,expected=expectedAxisZoom(120,startX,pointerX,axis);await page.mouse.move(startX,axis.y);await page.mouse.down();await page.mouse.move(pointerX,axis.y,{steps:5});await page.mouse.up();await page.waitForTimeout(100);const settings=await readSettings(page);if(settings.visibleBars!==expected||settings.panBars!==0)throw new Error(`desktop time-axis scale mismatch: ${JSON.stringify({axis,startX,pointerX,expected,settings})}`);
    const paneY=await page.evaluate(()=>{const rect=document.querySelector("#binance-rsi-mtf-host").shadowRoot.querySelector(".rsi-canvas").getBoundingClientRect();return rect.top+Math.min(80,rect.height/2)});await page.mouse.move(axis.left+axis.width*.6,paneY);await page.mouse.down();await page.mouse.move(axis.left+axis.width*.6-120,paneY,{steps:4});await page.mouse.up();await page.waitForTimeout(100);const shifted=await readSettings(page);if(!(shifted.panBars<0))throw new Error(`desktop future offset setup failed: ${JSON.stringify(shifted)}`);const secondStart=axis.left+axis.width*.45,secondPointer=secondStart+100,secondExpected=expectedAxisZoom(shifted.visibleBars,secondStart,secondPointer,axis);await page.mouse.move(secondStart,axis.y);await page.mouse.down();await page.mouse.move(secondPointer,axis.y,{steps:4});await page.mouse.up();await page.waitForTimeout(100);const preserved=await readSettings(page);if(preserved.visibleBars!==secondExpected||preserved.panBars!==shifted.panBars)throw new Error(`desktop future offset changed while scaling: ${JSON.stringify({shifted,preserved,secondExpected})}`);console.log(`desktop time-axis drag: ${settings.visibleBars} bars, future offset ${preserved.panBars} preserved`);await context.close();
  }
  {
    const context=await browser.newContext({viewport:{width:390,height:700},isMobile:true,hasTouch:true,deviceScaleFactor:2,serviceWorkers:"block"}),page=await context.newPage();await page.goto(`${base}?symbol=BTCUSDT`,{waitUntil:"domcontentloaded"});await page.waitForFunction(()=>document.querySelector("#binance-rsi-mtf-host")?.shadowRoot?.querySelector(".status")?.dataset.state==="live",null,{timeout:30000});
    const axis=await timeAxisRect(page),startX=axis.left+axis.width*.35,pointerX=startX+70,expected=expectedAxisZoom(120,startX,pointerX,axis),cdp=await context.newCDPSession(page);await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:startX,y:axis.y,id:1}]});for(let step=1;step<=5;step++)await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:startX+(pointerX-startX)*step/5,y:axis.y,id:1}]});await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await page.waitForTimeout(100);const settings=await readSettings(page);if(settings.visibleBars!==expected||settings.panBars!==0)throw new Error(`touch time-axis scale mismatch: ${JSON.stringify({axis,startX,pointerX,expected,settings})}`);console.log(`touch time-axis drag: ${settings.visibleBars} bars, right offset preserved`);await context.close();
  }
  for(const width of[320,390,591])for(const deviceScaleFactor of[1,1.25,2]){
    const context=await browser.newContext({viewport:{width,height:700},deviceScaleFactor,isMobile:true,hasTouch:true,serviceWorkers:"block"}),page=await context.newPage();await page.goto(`${base}?symbol=BTCUSDT`,{waitUntil:"domcontentloaded"});await page.waitForFunction(()=>document.querySelector("#binance-rsi-mtf-host")?.shadowRoot?.querySelectorAll(".topbar .tab").length===11,null,{timeout:30000});
    const alignment=await page.evaluate(()=>{const shadow=document.querySelector("#binance-rsi-mtf-host").shadowRoot,tabs=[...shadow.querySelectorAll(".topbar .tab")],labels=tabs.map(tab=>tab.textContent),measure=tab=>{const box=tab.getBoundingClientRect(),range=document.createRange();range.selectNodeContents(tab);const text=range.getBoundingClientRect(),style=getComputedStyle(tab);return{label:tab.textContent,deltaX:(text.left+text.width/2)-(box.left+box.width/2),deltaY:(text.top+text.height/2)-(box.top+box.height/2),display:style.display,align:style.alignItems,justify:style.justifyContent,lineHeight:style.lineHeight,boxSizing:style.boxSizing,clipped:text.top<box.top-0.5||text.bottom>box.bottom+0.5}};const normal=tabs.map(measure),active=tabs.map(tab=>{tabs.forEach(item=>item.classList.remove("active"));tab.classList.add("active");return measure(tab)});return{labels,normal,active}});
    const expected=["30m","H1","H2","H4","H8","H12","D","3D","1W","2W","M"],invalid=[...alignment.normal,...alignment.active].filter(item=>Math.abs(item.deltaX)>0.75||Math.abs(item.deltaY)>0.75||item.display!=="flex"||item.align!=="center"||item.justify!=="center"||item.lineHeight!=="12px"||item.boxSizing!=="border-box"||item.clipped);if(JSON.stringify(alignment.labels)!==JSON.stringify(expected)||invalid.length)throw new Error(`${width}px DPR ${deviceScaleFactor} timeframe alignment failed: ${JSON.stringify({alignment,invalid})}`);await page.screenshot({type:"png"});console.log(`${width}px DPR ${deviceScaleFactor}: all timeframe labels centered`);await context.close();
  }
  for(const deviceScaleFactor of[1,1.25,1.5,2]){
    const context=await browser.newContext({viewport:{width:1280,height:800},deviceScaleFactor,serviceWorkers:"block"}),page=await context.newPage();await page.goto(`${base}?symbol=BTCUSDT`,{waitUntil:"domcontentloaded"});await page.waitForFunction(()=>document.querySelector("#binance-rsi-mtf-host")?.shadowRoot?.querySelector(".status")?.dataset.state==="live",null,{timeout:30000});
    const pixels=await page.evaluate(()=>{const canvas=document.querySelector("#binance-rsi-mtf-host").shadowRoot.querySelector(".price-canvas"),rect=canvas.getBoundingClientRect(),scaleX=canvas.width/rect.width,scaleY=canvas.height/rect.height,data=canvas.getContext("2d").getImageData(0,0,canvas.width,canvas.height).data,isBlack=(x,y)=>{const offset=(y*canvas.width+x)*4;return data[offset]<8&&data[offset+1]<8&&data[offset+2]<8&&data[offset+3]>245},expected=Math.max(1,Math.round(scaleX)),runs=[];for(const index of[15,30,45,60,75,90,105]){const raw=8+index/119*(rect.width-82),center=Math.round(raw*scaleX-expected/2)+expected/2;let shortest=Infinity;for(let y=Math.round(8*scaleY);y<Math.round((rect.height-8)*scaleY);y++){let seed=null;for(const candidate of[...new Set([Math.floor(center),Math.ceil(center)])])if(isBlack(candidate,y)){seed=candidate;break}if(seed===null)continue;let left=seed,right=seed;while(left>0&&isBlack(left-1,y))left--;while(right+1<canvas.width&&isBlack(right+1,y))right++;shortest=Math.min(shortest,right-left+1)}if(Number.isFinite(shortest))runs.push(shortest)}return{actualDpr:devicePixelRatio,backing:[canvas.width,canvas.height],expectedBacking:[Math.round(rect.width*devicePixelRatio),Math.round(rect.height*devicePixelRatio)],expectedWickPixels:expected,runs}});
    if(pixels.backing[0]!==pixels.expectedBacking[0]||pixels.backing[1]!==pixels.expectedBacking[1]||pixels.runs.length<5||pixels.runs.some(width=>width!==pixels.expectedWickPixels))throw new Error(`DPR ${deviceScaleFactor} pixel alignment failed: ${JSON.stringify(pixels)}`);console.log(`DPR ${deviceScaleFactor}: ${pixels.expectedWickPixels}px crisp candle wicks`);await context.close();
  }
}finally{await browser.close()}
