import{readFile,readdir}from"node:fs/promises";import{join}from"node:path";import{fileURLToPath}from"node:url";
const root=new URL("../web/",import.meta.url),required=["index.html","styles.css","manifest.webmanifest","sw.js","assets/icon.svg","assets/icon-180.png","assets/icon-192.png","assets/icon-512.png","firebase-config.js","js/app.js","js/config.js","js/title-price.js","js/viewport.js","js/math.js","js/storage.js","js/storage-adapter.js","js/binance.js","js/firebase-sync.js","js/sync-core.js","js/chart-engine.js"],runtimeShell=required.filter(path=>!["sw.js","js/math.js","js/binance.js"].includes(path));
for(const path of required)await readFile(new URL(path,root));
const manifest=JSON.parse(await readFile(new URL("manifest.webmanifest",root),"utf8"));if(manifest.start_url!=="./"||manifest.scope!=="./"||manifest.display!=="standalone")throw new Error("Invalid Pages-relative PWA manifest");
const iconSvg=await readFile(new URL("assets/icon.svg",root),"utf8");if(!/^<svg\b[\s\S]*<\/svg>\s*$/.test(iconSvg)||!/viewBox="0 0 128 128"/.test(iconSvg))throw new Error("Invalid ChartForge SVG icon");if(/<(?:filter|linearGradient|radialGradient|image|text)\b/i.test(iconSvg)||/\b(?:filter|style)=/i.test(iconSvg))throw new Error("ChartForge icon must remain a flat, hand-authored vector");
if(/\bstroke=/i.test(iconSvg)||!iconSvg.includes('fill="#20242c"')||!iconSvg.includes('fill="#6750d8"'))throw new Error("ChartForge datum mark must retain its fill-only charcoal and violet construction");
const expectedIcons=new Map([["./assets/icon.svg","any"],["./assets/icon-192.png","192x192"],["./assets/icon-512.png","512x512"]]);for(const[src,sizes]of expectedIcons){const icon=manifest.icons?.find(item=>item.src===src);if(!icon||icon.sizes!==sizes)throw new Error(`Manifest misses ${src} (${sizes})`)}
for(const size of[180,192,512]){const png=await readFile(new URL(`assets/icon-${size}.png`,root));if(png.length<24||png.toString("hex",0,8)!=="89504e470d0a1a0a"||png.readUInt32BE(16)!==size||png.readUInt32BE(20)!==size)throw new Error(`Invalid ${size}x${size} PWA icon`)}
const sw=await readFile(new URL("sw.js",root),"utf8");for(const path of runtimeShell)if(!sw.includes(`\"./${path}\"`)&&!sw.includes(`\"./\"`))throw new Error(`Service worker misses ${path}`);for(const path of ["js/math.js","js/binance.js"])if(sw.includes(`\"./${path}\"`))throw new Error(`Service worker caches unused module ${path}`);
const css=await readFile(new URL("styles.css",root),"utf8");if(!css.includes("#pwa-bootstrap[hidden]"))throw new Error("bootstrap hidden state must override its visible layout");
const html=await readFile(new URL("index.html",root),"utf8");if(!html.includes('id="pwa-bootstrap"'))throw new Error("Missing PWA bootstrap status");if(!html.includes('rel="icon" href="./assets/icon.svg"')||!html.includes('rel="apple-touch-icon" href="./assets/icon-180.png"'))throw new Error("Browser icon references are incomplete");if(/<button\b|data-tool=/.test(html))throw new Error("Legacy duplicate controls remain outside the canonical Shadow DOM");
async function walk(dir){let files=[];for(const item of await readdir(dir,{withFileTypes:true})){const p=join(dir,item.name);files=item.isDirectory()?files.concat(await walk(p)):files.concat(p)}return files}
for(const file of await walk(fileURLToPath(root))){if(!/\.(js|html|css)$/.test(file))continue;const source=await readFile(file,"utf8");if(/\bchrome\s*\.(?:runtime|storage)/.test(source))throw new Error(`Legacy browser API found in PWA source: ${file}`)}
console.log(`PWA manifest ${manifest.name}; ${required.length} app-shell files validated.`);
