import{readFile,readdir}from"node:fs/promises";import{join}from"node:path";import{fileURLToPath}from"node:url";
const root=new URL("../web/",import.meta.url),required=["index.html","styles.css","manifest.webmanifest","sw.js","assets/icon.svg","firebase-config.js","js/app.js","js/config.js","js/title-price.js","js/math.js","js/storage.js","js/storage-adapter.js","js/binance.js","js/firebase-sync.js","js/sync-core.js","js/canonical-content.js"],runtimeShell=required.filter(path=>!["sw.js","js/math.js","js/binance.js"].includes(path));
for(const path of required)await readFile(new URL(path,root));
const manifest=JSON.parse(await readFile(new URL("manifest.webmanifest",root),"utf8"));if(manifest.start_url!=="./"||manifest.scope!=="./"||manifest.display!=="standalone")throw new Error("Invalid Pages-relative PWA manifest");
const sw=await readFile(new URL("sw.js",root),"utf8");for(const path of runtimeShell)if(!sw.includes(`\"./${path}\"`)&&!sw.includes(`\"./\"`))throw new Error(`Service worker misses ${path}`);for(const path of ["js/math.js","js/binance.js"])if(sw.includes(`\"./${path}\"`))throw new Error(`Service worker caches unused module ${path}`);
const css=await readFile(new URL("styles.css",root),"utf8");if(!css.includes("#pwa-bootstrap[hidden]"))throw new Error("bootstrap hidden state must override its visible layout");
const html=await readFile(new URL("index.html",root),"utf8");if(!html.includes('id="pwa-bootstrap"'))throw new Error("Missing PWA bootstrap status");if(/<button\b|data-tool=/.test(html))throw new Error("Legacy duplicate controls remain outside the canonical Shadow DOM");
async function walk(dir){let files=[];for(const item of await readdir(dir,{withFileTypes:true})){const p=join(dir,item.name);files=item.isDirectory()?files.concat(await walk(p)):files.concat(p)}return files}
for(const file of await walk(fileURLToPath(root))){if(!/\.(js|html|css)$/.test(file))continue;const source=await readFile(file,"utf8");if(!file.endsWith("canonical-content.js")&&/\bchrome\s*\./.test(source))throw new Error(`Chrome API found outside canonical compatibility layer: ${file}`)}
const canonical=await readFile(new URL("js/canonical-content.js",root),"utf8");if(!/\bchrome\s*\./.test(canonical))throw new Error("Canonical extension source unexpectedly lost its Chrome compatibility calls");
console.log(`PWA manifest ${manifest.name}; ${required.length} canonical app-shell files validated.`);
